# -*- coding: utf-8 -*-

 # Form implementation generated from reading ui file 'EditorWindow.ui'
 #
 # Created by: PyQt5 UI code generator 5.15.4
 #
 # WARNING: Any manual changes made to this file will be lost when pyuic5 is
 # run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import general_TA_simulator 

 #pass in system 
 #editor window pass in whole engine 
 #engine gives tools to get assmelies and it stores moves and stuff 
 #engine is good > system cause it has what we need and more


class Ui_EditorWindow(object):
     def setupUi(self, EditorWindow):
         EditorWindow.setObjectName("EditorWindow")
         EditorWindow.resize(813, 586)
         font = QtGui.QFont()
         font.setFamily("Menlo")
         EditorWindow.setFont(font)
         EditorWindow.setToolTipDuration(-2)
         EditorWindow.setStyleSheet("")
         self.centralwidget = QtWidgets.QWidget(EditorWindow)
         self.centralwidget.setStyleSheet("")
         self.centralwidget.setObjectName("centralwidget")
         self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
         self.verticalLayout.setObjectName("verticalLayout")
         self.editFrame = QtWidgets.QFrame(self.centralwidget)
         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
         sizePolicy.setHorizontalStretch(0)
         sizePolicy.setVerticalStretch(0)
         sizePolicy.setHeightForWidth(self.editFrame.sizePolicy().hasHeightForWidth())
         self.editFrame.setSizePolicy(sizePolicy)
         self.editFrame.setMaximumSize(QtCore.QSize(16777215, 500))
         self.editFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
         self.editFrame.setFrameShadow(QtWidgets.QFrame.Raised)
         self.editFrame.setObjectName("editFrame")
         self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.editFrame)
         self.verticalLayout_2.setObjectName("verticalLayout_2")
         self.toolBox = QtWidgets.QToolBox(self.editFrame)
         self.toolBox.setObjectName("toolBox")
         self.page = QtWidgets.QWidget()
         self.page.setGeometry(QtCore.QRect(0, 0, 765, 340))
         self.page.setMinimumSize(QtCore.QSize(0, 340))
         self.page.setObjectName("page")
         self.label = QtWidgets.QLabel(self.page)
         self.label.setGeometry(QtCore.QRect(30, 30, 60, 16))
         self.label.setObjectName("label")
         self.comboBox = QtWidgets.QComboBox(self.page)
         self.comboBox.setGeometry(QtCore.QRect(90, 20, 91, 32))
         self.comboBox.setObjectName("comboBox")
         self.toolBox.addItem(self.page, "")
         self.page_2 = QtWidgets.QWidget()
         self.page_2.setGeometry(QtCore.QRect(0, 0, 765, 340))
         self.page_2.setObjectName("page_2")


         self.tableWidget = QtWidgets.QTableWidget(self.page_2)
         self.tableWidget.setGeometry(QtCore.QRect(0, 70, 771, 261))
         self.tableWidget.setObjectName("tableWidget")
         self.tableWidget.setColumnCount(4)
         columns = ['Color', 'Label', 'Seed', 'Initial']
         self.tableWidget.setColumnWidth(0, 250)
         self.tableWidget.setColumnWidth(1, 250)
         self.tableWidget.setColumnWidth(2, 150)
         self.tableWidget.setColumnWidth(3, 150)
         self.tableWidget.setHorizontalHeaderLabels(columns)
         self.tableWidget.setRowCount(2)
         self.tableWidget.setRowHeight(0, 40)
         self.tableWidget.setRowHeight(1, 40)

          # 09/10 now need to bring in data from loaded xml stuff into tablewidget

         #self.loadData()

         # copy from general 

         # grab list for rules, turn back into dictionaries (functions)
     #def loadData(self):
        # connection = 

         self.toolBox.addItem(self.page_2, "")
         self.page_3 = QtWidgets.QWidget()
         self.page_3.setObjectName("page_3")
         self.toolBox.addItem(self.page_3, "")
         self.page_4 = QtWidgets.QWidget()
         self.page_4.setObjectName("page_4")
         self.toolBox.addItem(self.page_4, "")
         self.verticalLayout_2.addWidget(self.toolBox)
         self.verticalLayout.addWidget(self.editFrame)
         self.frame_2 = QtWidgets.QFrame(self.centralwidget)
         self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
         self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
         self.frame_2.setObjectName("frame_2")
         self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
         self.horizontalLayout.setObjectName("horizontalLayout")
         self.pushButton = QtWidgets.QPushButton(self.frame_2)
         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
         sizePolicy.setHorizontalStretch(0)
         sizePolicy.setVerticalStretch(0)
         sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
         self.pushButton.setSizePolicy(sizePolicy)
         self.pushButton.setObjectName("pushButton")
         self.horizontalLayout.addWidget(self.pushButton)
         self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
         sizePolicy.setHorizontalStretch(0)
         sizePolicy.setVerticalStretch(0)
         sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
         self.pushButton_2.setSizePolicy(sizePolicy)
         self.pushButton_2.setObjectName("pushButton_2")
         self.horizontalLayout.addWidget(self.pushButton_2)
         self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
         EditorWindow.setCentralWidget(self.centralwidget)

         self.retranslateUi(EditorWindow)
         self.toolBox.setCurrentIndex(1)
         QtCore.QMetaObject.connectSlotsByName(EditorWindow)

     def retranslateUi(self, EditorWindow):
         _translate = QtCore.QCoreApplication.translate
         EditorWindow.setWindowTitle(_translate("EditorWindow", "Editor "))
         self.label.setText(_translate("EditorWindow", "Temp:"))
         self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("EditorWindow", "System Temperature"))
         self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("EditorWindow", "Add State"))
         self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("EditorWindow", "Add Affinity Rule"))
         self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("EditorWindow", "Add Transition Rule"))
         self.pushButton.setText(_translate("EditorWindow", "Apply"))
         self.pushButton_2.setText(_translate("EditorWindow", "Save as"))


if __name__ == "__main__":
     import sys
     app = QtWidgets.QApplication(sys.argv)
     EditorWindow = QtWidgets.QMainWindow()
     ui = Ui_EditorWindow()
     ui.setupUi(EditorWindow)
     EditorWindow.show()
     sys.exit(app.exec_())